
-- schema definition, spring only executes this automatically for embedded in-memory databases

create table recipes (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,          -- must match Recipe.name constraint
    instructions varchar(2048) not null, -- must match Recipe.instructions constraint
    category integer, -- see RecipeCategory for the integer values
    nof_servings integer
);

create table ingredients (
    id bigint generated by default as identity primary key,
    name varchar(255) unique not null -- must match Ingredient.name constraint
);

create table recipe_ingredient (
    recipe bigint references recipes,
    ingredient bigint references ingredients
);
